### ISSUE TITLE
Please release `[static-ace]` support.

### ISSUE THREAD

**Issue by greyhare** [django-cms/djangocms-snippet#124]
I have Django CMS installed via pip, and the latest version of this plugin is 3.0.0 released two years ago.

I'm having the same issue as django-cms/djangocms-frontend#48. I see that commit 0764195 should fix this issue. Please release an update with this fix.

Thanks!

**Comment by marksweb** [comment]
https://pypi.org/project/djangocms-snippet/3.1.0/
